enum joint_id {
    ID_R_SHOULDER_PITCH = 1,
    ID_L_SHOULDER_PITCH = 2,
    ID_R_SHOULDER_ROLL = 3,
    ID_L_SHOULDER_ROLL = 4,
    ID_R_ELBOW = 5,
    ID_L_ELBOW = 6,
    ID_R_HIP_YAW = 7,
    ID_L_HIP_YAW = 8,
    ID_R_HIP_ROLL = 9,
    ID_L_HIP_ROLL = 10,
    ID_R_HIP_PITCH = 11,
    ID_L_HIP_PITCH = 12,
    ID_R_KNEE = 13,
    ID_L_KNEE = 14,
    ID_R_ANKLE_PITCH = 15,
    ID_L_ANKLE_PITCH = 16,
    ID_R_ANKLE_ROLL = 17,
    ID_L_ANKLE_ROLL = 18,
    ID_HEAD_PAN = 19,
    ID_HEAD_TILT = 20,
    NUMBER_OF_JOINTS
};
const int CENTER_VALUE = 2048;
int RL_GYRO(0);
int FB_GYRO(0);
